### ISSUE TITLE
Libraries folder not persisted

### ISSUE THREAD

**Issue by nicolas-mosch** [bitnami/bitnami-docker-drupal#102]
It seems the libraries folder is not being included from the persistent storage. I added my libraries folder to the persisted root (next to modules, themes, sites etc. in persistent volume) and I still get a missing library error. If I add a symlink pointing to that libraries folder in the Drupal installation folder, then it works. This symlink, of course, is not persistent. Adding the libraries folder in the persisted sites/default/ folder is not sufficient (same error). After some research online, it seems the correct location for the libraries folder is in the root, and not in sites/default anyways.

**Comment by marcosbc** [comment]
Hi @nicolas-mosch, note that `library` is not an official directory of Drupal.

In any case, you may be able to fix by moving the entire `library` directory to `/bitnami/drupal`, and then use a new Drupal docker image based on the Bitnami one:

- Stop all services: `docker-compose down`
- Create a new Dockerfile:

      FROM bitnami/drupal:latest

      RUN ln -s /bitnami/drupal/library /opt/bitnami/drupal/library

- Build the Docker image:

      docker build -t mydrupal .

- Update the Drupal image in your docker-compose.yml:

      drupal:
        image: 'mydrupal'

- Start again: `docker-compose up`

Now anything stored inside `library` should be persisted.

**Comment by gattoniDEPT** [comment]
Drupal is looking for **libraries** directory, not library, so maybe the right Dockerfile should be:

```
FROM bitnami/drupal:latest
RUN ln -s /bitnami/drupal/libraries /opt/bitnami/drupal/libraries
```

**Comment by marcosbc** [comment]
You're right @gattoniDEPT, I've modified my comment. Thanks for pointing it out.
