### ISSUE TITLE
Best practice for drush tasks after installation

### ISSUE THREAD

**Issue by mikkeschiren** [bitnami/bitnami-docker-drupal#108]
Trying to figure out how to change the drush site:install or to add tasks after that, but seems that I am blind... Where does the site:install command run from?

What I would like to do: adding a different sync directory in settings.php, and running drush config:import after site install.

**Comment by alemorcuq** [comment]
Hi, @mikkeschiren.

The `drush site:install` command is run from `/root/.nami/components/com.bitnami.drupal/main.js`, which is being called from: https://github.com/bitnami/bitnami-docker-drupal/blob/fa53fb981ea4d32221d7ae6d85a04aed33f7d5fc/8/debian-9/rootfs/app-entrypoint.sh#L11

So maybe you can modify the `/app-entrypoint.sh` to execute your changes after the `nami_initialize` step.

Regards,
Alejandro

**Comment by mikkeschiren** [comment]
Ahh great thanks @alemorcuq - that solves it. Closing the issue.
