### ISSUE TITLE
Error in Drupal  post-installation step: Group '40023' not found

### ISSUE THREAD

**Issue by deepak71** [bitnami/bitnami-docker-drupal#111]
**Description**
Error in executing Drupal post-installation step While launching Drupal pod on K8s platform that uses EFS PVC for drupal data.

**Steps to reproduce the issue:**

1. Helm install my-release drupal
2.  After that getting below message:
**Error executing 'postInstallation': Group '40023' not found**

**Describe the results you received:**
After setting NAMI_LOG_LEVEL=trace in drupal POD, we received below error message:
```
drupal  INFO  Cleaning the cache..
drupal  TRACE [runProgram] Executing: /opt/bitnami/drupal/vendor/bin/drush cr
Error executing 'postInstallation': 
In EntityTypeManager.php line 150:
                                           
  The "block" entity type does not exist.  
                                           

cache:rebuild [--cache-clear [CACHE-CLEAR]] [--no-cache-clear] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command>


nami    TRACE Error: Error executing 'postInstallation': 

    at runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/run-program.js:223:14)
    at Object.runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/index.js:63:12)
    at Object.$app.helpers.drush (/root/.nami/components/com.bitnami.drupal/helpers.js:71:7)
    at Object.$app.helpers.flushCache (/root/.nami/components/com.bitnami.drupal/helpers.js:53:16)
    at Component.$app.postInstallation (/root/.nami/components/com.bitnami.drupal/main.js:75:18)
    at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Component.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
```

**Comment by rafariossaa** [comment]
Hi,
  I don't a similar environment to test with.
  At that point it is trying to run: `drush rc` to flush the cache. This will remove files and it will need the proper permissions. 
  Could you provide the full log where the message `group 40023` appears ?
  Could you try with other kind of PVC ?

**Comment by deepak71** [comment]
Hi,
I started it from scratch again like using new mysql db and enabled drupal env tracing. In this, we're using AWS EFS backed PVC for drupal data. We got following error message:

`
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/tmp"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/tmp
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/logs"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/logs
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/var","/opt/bitnami/php/var/log","/opt/bitnami/php/var/run"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/log
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/run
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing drupal
drupal  DEBUG Creating the Apache configuration vhost file
drupal  DEBUG Creating the Apache configuration https vhost file
drupal  INFO  Preparing PHP environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mysql-local:3306
mysql-c TRACE [canConnect] Testing connection with 'root' user
mysql-c TRACE [showDatabases] Getting databases for 'root' user
mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hmysql-local -uroot -p****** -e SHOW DATABASES;
mysql-c TRACE [execute] Result: {"code":0,"stdout":"information_schema\nmy_database\nmysql\nperformance_schema\nsys\n","stderr":""}
mysql-c TRACE [showDatabases] Databases: information_schema
my_database
mysql
performance_schema
sys

mysql-c TRACE [canConnect] Connection with 'root' user is successful
mysql-c INFO  MySQL server listening and working at mysql-local:3306
drupal  DEBUG Preparing Drupal environment...
drupal  INFO  Installing Drupal with drush...
drupal  TRACE [runProgram] Executing: /opt/bitnami/drupal/vendor/bin/drush site:install standard --db-url=mysql://root:******@mysql-local:3306/my_database2 --account-name=user --account-mail=user@example.com --account-pass=******* --site-name='My blog' --site-mail=user@example.com -y

drupal  TRACE [prepareDataToPersist] Preparing /opt/bitnami/drupal/sites to persist in /bitnami/drupal/sites
drupal  TRACE [prepareDataToPersist] Preparing /opt/bitnami/drupal/themes to persist in /bitnami/drupal/themes
drupal  TRACE [prepareDataToPersist] Preparing /opt/bitnami/drupal/modules to persist in /bitnami/drupal/modules
drupal  TRACE [prepareDataToPersist] Preparing /opt/bitnami/drupal/profiles to persist in /bitnami/drupal/profiles
drupal  INFO  Cleaning the cache..
drupal  TRACE [runProgram] Executing: /opt/bitnami/drupal/vendor/bin/drush cr

drupal  TRACE [configurePermissions] File to chown: /bitnami/drupal/themes
drupal  TRACE [configurePermissions] File to chown: /bitnami/drupal/modules
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default/files
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 19 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 18 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 17 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 16 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 15 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 14 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 13 remaining attempts
drupal  TRACE [configurePermissions] File to chown: /opt/bitnami/drupal/sites/default
drupal  TRACE [retry] Trying to configure permissions... 12 remaining attempts
`
We tried with EBS backed PVC and with that Drupal successfully initialized.

**Comment by rafariossaa** [comment]
Hi,  
  Our CI/CD test the charts in regular configurations of K8s.
  Could you check this [thread](https://github.com/bitnami/charts/issues/1514) of an older issue related with EFS ?

**Comment by deepak71** [comment]
Thank you! it was related to EFS backed PVC. Actually, EFS backed PVC was not allowing us to have right permission for www-data user on /bitnami/drupal defined directory for drupal container.
