### ISSUE TITLE
After restart The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable.

### ISSUE THREAD

**Issue by maggie-drupal** [bitnami/bitnami-docker-drupal#117]
We have a Drupal installation using the bitnami drupal helm chart.
We had to restart our mariadb and after this it doesn't restart.
We get the following:

mariadb 12:27:46.16 INFO  ==> ** Starting MariaDB setup **
mariadb 12:27:46.19 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 12:27:46.21 INFO  ==> Initializing mariadb database
mariadb 12:27:46.25 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable.
 Configurations based on environment variables will not be applied for this file.
mariadb 12:27:46.26 INFO  ==> Using persisted data
mariadb 12:27:46.32 INFO  ==> Running mysql_upgrade
mariadb 12:27:46.36 INFO  ==> Starting mariadb in background
mariadb 12:27:48.44 INFO  ==> Stopping mariadb

**Comment by FraPazGal** [comment]
Hi @maggie-drupal,

Thanks for the issue! I haven't been able to reproduce your issue. From what I understand, the warning is the standard behaviour of the pod and it should not be the reason as to why it is not working correctly. Could you share the output of the mariadb pod using the value `--set mariadb.debug=true` in the chart installation? Also, please provide what version of the chart and of kubectl you are using. 

Thanks in advance.
