### ISSUE TITLE
Why is code persisted?

### ISSUE THREAD

**Issue by maggie-drupal** [bitnami/bitnami-docker-drupal#118]
By default when the container starts for the first time, it does the following:
It sets up drupal and persists  sites/ themes/ modules/ profiles/.
When the container is restarted it does the following:
Checks if persistent folder (bitnami/drupal) exists and not empty and if true
Restores everything from the persistent folder.

I don't understand why this happens. If I install custom or contributed modules, after container restart they are lost because the code (modules, themes folders) are restored from persistence.

I overcome this by changing the DRUPAL_DATA_TO_PERSIST, to persist only sites.

Am I missing something?

**Comment by miguelaeh** [comment]
Hi @maggie-drupal ,
I think custom modeules should not be lost since there is a symlink from the installation folder to the persisted one, so actually, the custom modules should be at the volume.
How are you n installing it? In case of docker-compose soulc you share it?

**Comment by maggie-drupal** [comment]
This is my docker-compose:
`version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_drupal
      - MARIADB_DATABASE=bitnami_drupal
    volumes:
      - 'C:\dev\mariadb_data:/bitnami/mariadb'
  drupal:
    build: .
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DRUPAL_DATABASE_HOST=mariadb
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_DATABASE_NAME=bitnami_drupal
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'C:\dev\drupal_data:/bitnami/drupal'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  drupal_data:
    driver: local
`

This is my dockerfile:
`FROM bitnami/drupal:9.0.6-debian-10-r0

ENV DRUPAL_DATA_TO_PERSIST="sites/ themes/ modules/ profiles/"
USER root
#Install tools
RUN apt-get update && apt-get install -y \
	git \
	vim \
	wget \
    curl


COPY custom_run.sh /
RUN chmod 755 /custom_run.sh
RUN mkdir custom_src
RUN chown 1001 custom_src


WORKDIR "custom_src"
COPY composer.json composer.lock ./
COPY modules /custom_src/modules
COPY themes /custom_src/themes
COPY config /custom_src
RUN composer install

WORKDIR "/"

#Switch back to 1001 user
USER 1001
ENTRYPOINT [ "/custom_run.sh" ]
`


and this is my custom_run.sh:
`#!/bin/bash -e
#    Copy the custom and contrib code to be persistent for the first run. Bitnami commands below will persist_app
echo "Starting custom configuration"
echo "Remove modules, themes and vendor folders"
rm -rf /opt/bitnami/drupal/modules
rm -rf /opt/bitnami/drupal/themes
rm -rf /opt/bitnami/drupal/vendor
rm -rf /opt/bitnami/drupal/libraries

echo "Copy custom modules folder"
cp -R /src/modules /opt/bitnami/drupal/modules
echo "Copy custom themes folder"
cp -R /src/themes /opt/bitnami/drupal/themes
echo "Copy vendor folder"
cp -R /src/vendor /opt/bitnami/drupal/vendor
echo "Copy libraries folder"
cp -R /src/libraries /opt/bitnami/drupal/libraries
echo "Copy composer files"
cp /src/composer.json /opt/bitnami/drupal/
cp /src/composer.lock /opt/bitnami/drupal/

echo "Bitnami Drupal setup actions"
echo "Bitnami apache setup"
/opt/bitnami/scripts/apache/setup.sh
echo "Bitnami PHP setup"
/opt/bitnami/scripts/php/setup.sh
echo "Bitnami MYSQL setup"
/opt/bitnami/scripts/mysql-client/setup.sh
echo "Bitnami DRUPAL setup"
/opt/bitnami/scripts/drupal/setup.sh
/post-init.sh
echo "Bitnami setup actions finished!"

cd /opt/bitnami/drupal

drush cr || echo "Tried to execute drush cr"

echo "Database update"
drush -y updb

echo "Setting the system site id"
drush -y cset "system.site" uuid "1ba733c4-7e83-4ba6-bbc3-8f1b5e426986" || echo "UUID is set"


echo "Getting the config_sync_directory directory"
SYNC_DIR=$(drush eval "print(\Drupal\Core\Site\Settings::get('config_sync_directory'))")
echo $SYNC_DIR
rm -rf /opt/bitnami/drupal/$SYNC_DIR/*
cp -ar /src/sync/* /opt/bitnami/drupal/$SYNC_DIR

echo "Configuration import"
drush -y config:import || drush -y config:import
drush cr || echo "Tried to execute drush cr"
echo "Finished custom configuration"

echo "Starting Apache"
/opt/bitnami/scripts/apache/run.sh
`

**Comment by miguelaeh** [comment]
Hi @maggie-drupal ,
I think your `/src` folder will be empty to perform the copy. I think it should be:
```
- cp -R /src/modules /opt/bitnami/drupal/modules
+ cp -R /custom_src/modules /opt/bitnami/drupal/modules
```
Apart from that it seems you are trying to copy folders that are not actually copied in the Dockerfile

**Comment by maggie-drupal** [comment]
I corrected this typo. Apart from this, to my understanding, I had the following error. I replaced the /opt/bitnami/drupal/modules, themes and composer files with my mine. Instead of this what I should have done and did, is to replace the persistent volume folder files with mine and then execute the /opt/bitnami/scripts/drupal/setup.sh which basically restore the files from persistence.

I have another question if you could help. What is the appropriate/recommended way of updating settings.php? 
I am thinking of touching it during deployment and add the settings I wish at the end of the file. Do you have something else to propose?

**Comment by miguelaeh** [comment]
Hi @maggie-drupal ,
If that file exist at build time I would make the modifications at the postunpack, to avoid making the same changes every time a new container is created. If that file is created at run time, then I think there is not other better approach since you will need to change it at deployment time
