### ISSUE TITLE
Azure AKS deployment failed. File settings.php not writable

### ISSUE THREAD

**Issue by nzlatev** [bitnami/bitnami-docker-drupal#123]
**Description**
Pod under AKS cluster filed to become to status "ready" due to the following error:
Use Helm chart to deploy application on AKS.
```
drupal 09:13:37.05 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
drupal 09:13:37.08 DEBUG ==> Validating settings in DRUPAL_* environment variables...
drupal 09:13:37.09 WARN  ==> The Drupal configuration file '/opt/bitnami/drupal/sites/default/settings.php' is not writable. Configurations based on environment variables will not be applied for this file.
drupal 09:13:37.17 INFO  ==> Trying to connect to the database server
drupal 09:13:37.17 DEBUG ==> Executing SQL command:
SELECT 1
1
drupal 09:13:37.25 INFO  ==> Configuring file permissions for Drupal
drupal 09:13:37.26 INFO  ==> An already initialized Drupal database was provided, configuration will be skipped
drupal 09:13:37.26 DEBUG ==> Upgrading Drupal database with drush...

In BootstrapHook.php line 32:
                                                                      
  Bootstrap failed. Run your command with -vvv for more information.  
                                                                      

updatedb [--cache-clear [CACHE-CLEAR]] [--entity-updates] [--post-updates [POST-UPDATES]]
```

Use Azure File Shares (StorageClass azurefile-premium). Volume mounted successfully with mountPath /bitnami/drupal, but there are missing directories sites/, modules/, themes/ and profiles/.
```
//f9933871caf1a4c759c5d96.file.core.windows.net/kubernetes-dynamic-pvc-ec81140c-242d-4f8c-bf05-ed78101a4d14 cifs      100G     0  100G   0% /var/lib/kubelet/pods/a6a96de6-5cf5-4de2-8aee-8a3922bd978f/volumes/kubernetes.io~azure-file/pvc-ec81140c-242d-4f8c-bf05-ed78101a4d14
```
DBase connectivity is OK and "SELECT 1" passed ok.

Function drupal_validate invoked from bash/shell script libdrupal.sh failed for some reason?!? 

```
drupal 15:54:49.69 DEBUG ==> Validating settings in DRUPAL_* environment variables...
+ local error_code=0
+ is_file_writable /opt/bitnami/drupal/sites/default/settings.php
+ local file=/opt/bitnami/drupal/sites/default/settings.php
+ local dir
++ dirname /opt/bitnami/drupal/sites/default/settings.php
+ dir=/opt/bitnami/drupal/sites/default
+ [[ -f /opt/bitnami/drupal/sites/default/settings.php ]]
+ [[ ! -f /opt/bitnami/drupal/sites/default/settings.php ]]
+ [[ -d /opt/bitnami/drupal/sites/default ]]
+ false
+ warn 'The Drupal configuration file '\''/opt/bitnami/drupal/sites/default/settings.php'\'' is not writable. Configurations based on environment variables will not be applied for this file.'
+ log '\033[38;5;3mWARN \033[0m ==> The Drupal configuration file '\''/opt/bitnami/drupal/sites/default/settings.php'\'' is not writable. Configurations based on environment variables will not be applied for this file.'
++ date '+%T.%2N '
```

Due to this docker containe/k8s pod failed to start.

**Steps to reproduce the issue:**

1. Create docker images and run it on local PC with the command provided on Readme.md
2. Deploy the same docker image with Helm chart on AKS cluster
3. docker containe/k8s pod created and failed to start 
4. kubectl get logs <pod>

**K8s pod failed to start **
```
[debug] Starting bootstrap to full [0.14 sec, 8.15 MB]
 [debug] Drush bootstrap phase 5 [0.14 sec, 8.15 MB]
 [debug] Try to validate bootstrap phase 5 [0.14 sec, 8.15 MB]
 [debug] Try to validate bootstrap phase 5 [0.14 sec, 8.15 MB]
 [debug] Try to bootstrap at phase 5 [0.14 sec, 8.15 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalRoot() [0.14 sec, 8.15 MB]
 [debug] Change working directory to /opt/bitnami/drupal [0.14 sec, 8.15 MB]
 [debug] Initialized Drupal 9.0.6 root directory at /opt/bitnami/drupal [0.14 sec, 8.31 MB]
 [debug] Try to validate bootstrap phase 5 [0.14 sec, 8.31 MB]
 [debug] Try to bootstrap at phase 5 [0.15 sec, 8.64 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalSite() [0.15 sec, 8.64 MB]
 [debug] Initialized Drupal site default at sites/default [0.15 sec, 8.87 MB]
 [debug] Try to validate bootstrap phase 5 [0.15 sec, 8.87 MB]
 [debug] Could not find a Drupal settings.php file at sites/default/settings.php. [0.15 sec, 8.87 MB]
 [debug] Try to bootstrap at phase 5 [0.15 sec, 8.87 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.15 sec, 8.87 MB]
 [debug] Add service modifier [0.15 sec, 9.01 MB]
 [debug] Try to validate bootstrap phase 5 [0.15 sec, 9.01 MB]
 [debug] Unable to connect to database. More information may be available by running `drush status`. This may occur when Drush is trying to bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for details. [0.15 sec, 9.08 MB]
 [debug] Could not bootstrap at phase 5 [0.15 sec, 9.06 MB]

In BootstrapHook.php line 32:
                                                                      
  [Exception]                                                         
  Bootstrap failed. Run your command with -vvv for more information.  
                                                                      

Exception trace:
  at /opt/bitnami/drupal/vendor/drush/drush/src/Boot/BootstrapHook.php:32
 Drush\Boot\BootstrapHook->initialize() at /opt/bitnami/drupal/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:44
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->doInitializeHook() at /opt/bitnami/drupal/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:36
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook() at /opt/bitnami/drupal/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:29
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize() at /opt/bitnami/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php:145
 Consolidation\AnnotatedCommand\CommandProcessor->initializeHook() at /opt/bitnami/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:296
 Consolidation\AnnotatedCommand\AnnotatedCommand->initialize() at /opt/bitnami/drupal/vendor/symfony/console/Command/Command.php:221
 Symfony\Component\Console\Command\Command->run() at /opt/bitnami/drupal/vendor/symfony/console/Application.php:1018
 Symfony\Component\Console\Application->doRunCommand() at /opt/bitnami/drupal/vendor/symfony/console/Application.php:271
 Symfony\Component\Console\Application->doRun() at /opt/bitnami/drupal/vendor/symfony/console/Application.php:147
 Symfony\Component\Console\Application->run() at /opt/bitnami/drupal/vendor/drush/drush/src/Runtime/Runtime.php:118
 Drush\Runtime\Runtime->doRun() at /opt/bitnami/drupal/vendor/drush/drush/src/Runtime/Runtime.php:49
 Drush\Runtime\Runtime->run() at /opt/bitnami/drupal/vendor/drush/drush/drush.php:72
 require() at /opt/bitnami/drupal/vendor/drush/drush/drush:4

updatedb [--cache-clear [CACHE-CLEAR]] [--entity-updates] [--post-updates [POST-UPDATES]] [--no-cache-clear] [--no-post-updates] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command>
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:
AKS version 1.18.14

```
Docker version on my pc:
Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17

Docker version on AKS node
Server:
 Engine:
  Version:          19.03.14+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
```

- Output of `docker info`:
```
Client:
 Debug Mode: false

Server:
 Containers: 19
  Running: 17
  Paused: 0
  Stopped: 2
 Images: 130
 Server Version: 19.03.14+azure
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765aba0d05254012b0b9e595e995c09186427f
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1039-azure
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.775GiB
 Name: aks-agentpool-23989532-vmss000000
 ID: FWBC:EG4F:2EQE:5K2E:PINB:PFVK:24JK:NCBD:RL7C:YYF3:GXXS:SUKU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```
- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Mauraza** [comment]
Hi @nzlatev,

Did you use the `mountOptions` to mount the PVC? Could you share the options you configure the volume?

**Comment by nzlatev** [comment]
> Hi @nzlatev,
> 
> Did you use the `mountOptions` to mount the PVC? Could you share the options you configure the volume?

nekms@wbgbox-VirtualBox:~/aksk8sdev/charts/bitnami/drupal$ kubectl describe pv pvc-ec81140c-242d-4f8c-bf05-ed78101a4d14
Name:            pvc-ec81140c-242d-4f8c-bf05-ed78101a4d14
Labels:          <none>
Annotations:     kubernetes.io/createdby: azure-file-dynamic-provisioner
                 pv.kubernetes.io/bound-by-controller: yes
                 pv.kubernetes.io/provisioned-by: kubernetes.io/azure-file
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    azurefile-premium
Status:          Bound
Claim:           raddev/cc-trace19-drupal-drupal
Reclaim Policy:  Delete
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        100Gi
Node Affinity:   <none>
Message:         
Source:
    Type:             AzureFile (an Azure File Service mount on the host and bind mount to the pod)
    SecretName:       azure-storage-account-f9933871caf1a4c759c5d96-secret
    SecretNamespace:  raddev
    ShareName:        kubernetes-dynamic-pvc-ec81140c-242d-4f8c-bf05-ed78101a4d14
    ReadOnly:         false
Events:               <none>

**Comment by Mauraza** [comment]
Hi @nzlatev,

Could you change the `uid` of the `volumeOptions` to `uid=1001` and tray again?

**Comment by nzlatev** [comment]
> Hi @nzlatev,
> 
> Could you change the `uid` of the `volumeOptions` to `uid=1001` and tray again?

Hi Mauraza,

you mean to change MountOptions of StorageClass azurefile-premium to be like these one:

MountOptions
         - dir_mode=0777
         - file_mode=0777
         - uid=1001
         - gid=1001

**Comment by Mauraza** [comment]
Hi @nzlatev, 

Yes, change the `mountOptions` to:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - mfsymlinks
  - nobrl

**Comment by nzlatev** [comment]
> Hi @nzlatev,
> 
> Yes, change the `mountOptions` to:
> 
> * dir_mode=0777
> * file_mode=0777
> * uid=1001
> * gid=1001
> * mfsymlinks
> * nobrl



Already did it, but the issue persist

Issue persist and file settings.php is not writable:

//<storageaccount>.file.core.windows.net/kubernetes-dynamic-pvc-0c8d5be2-0fd0-48a3-8429-33d9d1bd867b on /var/lib/kubelet/pods/4fee38c4-4f73-4aaf-bffe-0b1ea6590d6e/volumes/kubernetes.io~azure-file/pvc-0c8d5be2-0fd0-48a3-8429-33d9d1bd867b type cifs (rw,relatime,vers=3.0,cache=strict,username=febac48a9891749469e6e53,uid=1001,forceuid,gid=1001,forcegid,addr=52.239.220.232,file_mode=0777,dir_mode=0777,soft,persistenthandles,nounix,serverino,mapposix,mfsymlinks,rsize=1048576,wsize=1048576,bsize=1048576,echo_interval=60,actimeo=30)

-----

drupal 10:05:00.51 WARN  ==> The Drupal configuration file '/opt/bitnami/drupal/sites/default/settings.php' is not writablle. Configurations based on environment variables will not be applied for this file

**Comment by Mauraza** [comment]
Hi @nzlatev,

there is another case with drupal and azure is different but maybe that configuration can help you, could you check https://github.com/bitnami/charts/issues/5450?

**Comment by nzlatev** [comment]
> Hi @nzlatev,
> 
> there is another case with drupal and azure is different but maybe that configuration can help you, could you check [bitnami/charts#5450](https://github.com/bitnami/charts/issues/5450)?

This case is different, cause it's running with new instalation of drupal site.
In my case running with docker image by persist drupal sites/default directory and settings.php.
Values.yaml set with external mysql database, azurefile-premium storageClass, persistent volume and persistent volume claim.

**Comment by Mauraza** [comment]
Hi @nzlatev,

could you access the container of drupal and run the following command `ls -la /opt/bitnami/drupal/sites/default/`?

**Comment by nzlatev** [comment]
> Hi @nzlatev,
> 
> could you access the container of drupal and run the following command `ls -la /opt/bitnami/drupal/sites/default/`?

Status of pod is "CrashLoopBackOff" and that is not possible to exec command to list the directory. This directory exist, but when  volume is mount with mountPath "/bitnami/drupal" something happen with sites/default directory .

**Comment by Mauraza** [comment]
Could you add the `describe` of the pod of drupal and the deployment?

**Comment by nzlatev** [comment]
> Could you add the `describe` of the pod of drupal and the deployment?

Describe of pod and deployment


nekms@wbgbox-VirtualBox:~/aksk8sdev/fromds$ kubectl get pods
NAME                               READY   STATUS             RESTARTS   AGE
webappcc-drupal-6c44686865-zhlp5   0/1     CrashLoopBackOff   2          40s
nekms@wbgbox-VirtualBox:~/aksk8sdev/fromds$ kubectl get deployment
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
webappcc-drupal   0/1     1            0           45s
nekms@wbgbox-VirtualBox:~/aksk8sdev/fromds$ kubectl describe pod webappcc-drupal-6c44686865-zhlp5
Name:         webappcc-drupal-6c44686865-zhlp5
Namespace:    raddev
Priority:     0
Node:         aks-agentpool-99178659-vmss000002/10.168.38.227
Start Time:   Wed, 17 Mar 2021 09:32:37 +0200
Labels:       app.kubernetes.io/instance=webappcc
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=drupal
              helm.sh/chart=drupal-10.2.3
              pod-template-hash=6c44686865
Annotations:  prometheus.io/port: 9117
              prometheus.io/scrape: true
Status:       Running
IP:           10.168.39.66
IPs:
  IP:           10.168.39.66
Controlled By:  ReplicaSet/webappcc-drupal-6c44686865
Containers:
  webappcc-drupal:
    Container ID:   docker://48b9b74952272cdd2ae13c0abcaa7d110bcf7bab7755e78f759d8dd69d7ae3c9
    Image:          <registry>.azurecr.io/drupal/city-cred:latest
    Image ID:       docker-pullable://<registry>.azurecr.io/drupal/city-cred@sha256:d79ca3a16876276b053be647ec80ab71a3f8fd832696ede5ec5bd73c2e5ff82b
    Ports:          8080/TCP, 8443/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 17 Mar 2021 09:33:28 +0200
      Finished:     Wed, 17 Mar 2021 09:33:28 +0200
    Ready:          False
    Restart Count:  3
    Requests:
      cpu:     300m
      memory:  512Mi
    Environment:
      BITNAMI_DEBUG:                true
      ALLOW_EMPTY_PASSWORD:         no
      APACHE_HTTP_PORT_NUMBER:      8080
      APACHE_HTTPS_PORT_NUMBER:     8443
      DRUPAL_DATABASE_HOST:         rad-mysql-dev.mysql.database.azure.com
      DRUPAL_DATABASE_PORT_NUMBER:  3306
      DRUPAL_DATABASE_NAME:         citycred
      DRUPAL_DATABASE_USER:         radmysql
      DRUPAL_DATABASE_PASSWORD:     <set to the key 'db-password' in secret 'webappcc-drupal-externaldb'>  Optional: false
      DRUPAL_SKIP_BOOTSTRAP:        yes
      DRUPAL_PROFILE:               standard
      DRUPAL_USERNAME:              user
      DRUPAL_PASSWORD:              <set to the key 'drupal-password' in secret 'webappcc-drupal'>  Optional: false
      DRUPAL_EMAIL:                 user@example.com
    Mounts:
      /bitnami/drupal from drupal-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-88trg (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  drupal-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  webappcc-drupal-drupal
    ReadOnly:   false
  default-token-88trg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-88trg
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                            From                                        Message
  ----     ------            ----                           ----                                        -------
  Warning  FailedScheduling  <invalid>                      default-scheduler                           0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         <invalid>                      default-scheduler                           Successfully assigned raddev/webappcc-drupal-6c44686865-zhlp5 to aks-agentpool-99178659-vmss000002
  Normal   Pulling           <invalid> (x4 over <invalid>)  kubelet, aks-agentpool-99178659-vmss000002  Pulling image "<registry>.azurecr.io/drupal/city-cred:latest"
  Normal   Pulled            <invalid> (x4 over <invalid>)  kubelet, aks-agentpool-99178659-vmss000002  Successfully pulled image "<registry>.azurecr.io/drupal/city-cred:latest"
  Normal   Created           <invalid> (x4 over <invalid>)  kubelet, aks-agentpool-99178659-vmss000002  Created container webappcc-drupal
  Normal   Started           <invalid> (x4 over <invalid>)  kubelet, aks-agentpool-99178659-vmss000002  Started container webappcc-drupal
  Warning  BackOff           <invalid> (x5 over <invalid>)  kubelet, aks-agentpool-99178659-vmss000002  Back-off restarting failed container
nekms@wbgbox-VirtualBox:~/aksk8sdev/fromds$ kubectl describe deployment webappcc-drupal
Name:                   webappcc-drupal
Namespace:              raddev
CreationTimestamp:      Wed, 17 Mar 2021 09:32:38 +0200
Labels:                 app.kubernetes.io/instance=webappcc
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=drupal
                        helm.sh/chart=drupal-10.2.3
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: webappcc
                        meta.helm.sh/release-namespace: raddev
                        service.beta.kubernetes.io/azure-load-balancer-internal: true
Selector:               app.kubernetes.io/instance=webappcc,app.kubernetes.io/name=drupal
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       app.kubernetes.io/instance=webappcc
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=drupal
                helm.sh/chart=drupal-10.2.3
  Annotations:  prometheus.io/port: 9117
                prometheus.io/scrape: true
  Containers:
   webappcc-drupal:
    Image:       <registry>.azurecr.io/drupal/city-cred:latest
    Ports:       8080/TCP, 8443/TCP
    Host Ports:  0/TCP, 0/TCP
    Requests:
      cpu:     300m
      memory:  512Mi
    Environment:
      BITNAMI_DEBUG:                true
      ALLOW_EMPTY_PASSWORD:         no
      APACHE_HTTP_PORT_NUMBER:      8080
      APACHE_HTTPS_PORT_NUMBER:     8443
      DRUPAL_DATABASE_HOST:         <database>.mysql.database.azure.com
      DRUPAL_DATABASE_PORT_NUMBER:  3306
      DRUPAL_DATABASE_NAME:         <database>
      DRUPAL_DATABASE_USER:         radmysql
      DRUPAL_DATABASE_PASSWORD:     <set to the key 'db-password' in secret 'webappcc-drupal-externaldb'>  Optional: false
      DRUPAL_SKIP_BOOTSTRAP:        yes
      DRUPAL_PROFILE:               standard
      DRUPAL_USERNAME:              user
      DRUPAL_PASSWORD:              <set to the key 'drupal-password' in secret 'webappcc-drupal'>  Optional: false
      DRUPAL_EMAIL:                 user@example.com
    Mounts:
      /bitnami/drupal from drupal-data (rw)
  Volumes:
   drupal-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  webappcc-drupal-drupal
    ReadOnly:   false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      False   MinimumReplicasUnavailable
OldReplicaSets:  <none>
NewReplicaSet:   webappcc-drupal-6c44686865 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  0s    deployment-controller  Scaled up replica set webappcc-drupal-6c44686865 to 1

**Comment by Mauraza** [comment]
Hi @nzlatev,

Could you tell us why you set `DRUPAL_SKIP_BOOTSTRAP` to `yes`?

**Comment by nzlatev** [comment]
> Hi @nzlatev,
> 
> Could you tell us why you set `DRUPAL_SKIP_BOOTSTRAP` to `yes`?

This environment is set to "yes" cause no need for new installation of drupal site. I want to run kubernetes pod with already setup drupal site and the "sites" directory had copied into docker image and use it for kubernetes deployment.
So, in this case not empty "/bitnami/drupal" directory already exist into docker image and mountPath /bitnami/drupal used for kuberntes kind deployment at deployment.yaml file.

**Comment by Mauraza** [comment]
Hi @nzlatev,

Did you initialize the database too? without Bootstrap, the initial configuration of the database is need it.

**Comment by nzlatev** [comment]
> Hi @nzlatev,
> 
> Did you initialize the database too? without Bootstrap, the initial configuration of the database is need it.


 Did you initialize the database too? 

 sql inquiry "select 1" passed as the following:

DEBUG\033[0m ==> Executing SQL command:\nSELECT 1'
drupal 15:54:49.78 DEBUG ==> Executing SQL command:
SELECT 1
+ /opt/bitnami/mysql/bin/mysql -N -u radmysql dbname -pxxxx -h xxxx.mysql.database.azure.com -P 3306 --connect-timeout=5
1

About Bootstrap and mysql database, it's part of the xtrace output of the setup.sh:


 drush --root=/opt/bitnami/drupal -vvv updatedb
 [preflight] Config paths: /opt/bitnami/drupal/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /opt/bitnami/drupal/drush/sites,/opt/bitnami/drush/sites
 [preflight] Commandfile search paths: /opt/bitnami/drupal/vendor/drush/drush/src
 [debug] Starting bootstrap to full [0.14 sec, 8.15 MB]
 [debug] Drush bootstrap phase 5 [0.14 sec, 8.15 MB]
 [debug] Try to validate bootstrap phase 5 [0.14 sec, 8.15 MB]
 [debug] Try to validate bootstrap phase 5 [0.14 sec, 8.15 MB]
 [debug] Try to bootstrap at phase 5 [0.14 sec, 8.15 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalRoot() [0.14 sec, 8.15 MB]
 [debug] Change working directory to /opt/bitnami/drupal [0.14 sec, 8.15 MB]
 [debug] Initialized Drupal 9.0.6 root directory at /opt/bitnami/drupal [0.14 sec, 8.31 MB]
 [debug] Try to validate bootstrap phase 5 [0.14 sec, 8.31 MB]
 [debug] Try to bootstrap at phase 5 [0.15 sec, 8.64 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalSite() [0.15 sec, 8.64 MB]
 [debug] Initialized Drupal site default at sites/default [0.15 sec, 8.87 MB]
 [debug] Try to validate bootstrap phase 5 [0.15 sec, 8.87 MB]
 [debug] Could not find a Drupal settings.php file at sites/default/settings.php. [0.15 sec, 8.87 MB]
 [debug] Try to bootstrap at phase 5 [0.15 sec, 8.87 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.15 sec, 8.87 MB]
 [debug] Add service modifier [0.15 sec, 9.01 MB]
 [debug] Try to validate bootstrap phase 5 [0.15 sec, 9.01 MB]
 [debug] Unable to connect to database. More information may be available by running `drush status`. This may occur when Drush is trying to bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for details. [0.15 sec, 9.08 MB]
 [debug] Could not bootstrap at phase 5 [0.15 sec, 9.06 MB]

In BootstrapHook.php line 32:
                                                                      
  [Exception]                                                         
  Bootstrap failed. Run your command with -vvv for more information.  
                                                                      

Exception trace:
  at /opt/bitnami/drupal/vendor/drush/drush/src/Boot/BootstrapHook.php:32
 Drush\Boot\BootstrapHook->initialize() at /opt/bitnami/drupal/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:44
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->doInitializeHook() at /opt/bitnami/drupal/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:36
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher-

**Comment by Mauraza** [comment]
Hi @nzlatev,

```
[debug] Unable to connect to database. More information may be available by running drush status. This may occur when Drush is trying to bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the --uri parameter on the command line. See drush topic docs-aliases for details. [0.15 sec, 9.08 MB]
```

That makes sense, you need to initialize the database (by using a backup) or let the bootstrap be done.

**Comment by nzlatev** [comment]
> Hi @nzlatev,
> 
> ```
> [debug] Unable to connect to database. More information may be available by running drush status. This may occur when Drush is trying to bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the --uri parameter on the command line. See drush topic docs-aliases for details. [0.15 sec, 9.08 MB]
> ```
> 
> That makes sense, you need to initialize the database (by using a backup) or let the bootstrap be done.

Initializations of database depends of /bitnmi/drupal/sites/default/settings.php file. This file is no writable and accessible due to this the functions checking via libdrupal.sh script failed. Database is accessible, but the updatedb unable to complete dbase checking cause unable to get values for dbase credentials from setting.php file.

**Comment by Mauraza** [comment]
The errors come when is trying to execute dush 
https://github.com/bitnami/bitnami-docker-drupal/blob/79c95a60592f5ffceb252047f6ad547953e2a8a1/9/debian-10/rootfs/opt/bitnami/scripts/libdrupal.sh#L412-L415

You select to skip the bootstrap but the app is not really initialized

If you check this code
https://github.com/bitnami/bitnami-docker-drupal/blob/79c95a60592f5ffceb252047f6ad547953e2a8a1/9/debian-10/rootfs/opt/bitnami/scripts/libdrupal.sh#L124-L151

You can see in your logs appear that the application can connect to the database, and something fails when the process runs the command `drush`.

I think that the application directory wasn't persisted, because of this:
https://github.com/bitnami/bitnami-docker-drupal/blob/46db88088158c6a3aa361acfc6992ff0f8928b8c/9/debian-10/prebuildfs/opt/bitnami/scripts/libpersistence.sh#L105-L122

Could you try with `DRUPAL_SKIP_BOOTSTRAP` set to `no`?

**Comment by nzlatev** [comment]
> BITNAMI_VOLUME_DIR



> The errors come when is trying to execute dush
> https://github.com/bitnami/bitnami-docker-drupal/blob/79c95a60592f5ffceb252047f6ad547953e2a8a1/9/debian-10/rootfs/opt/bitnami/scripts/libdrupal.sh#L412-L415
> 
> You select to skip the bootstrap but the app is not really initialized
> 
> If you check this code
> https://github.com/bitnami/bitnami-docker-drupal/blob/79c95a60592f5ffceb252047f6ad547953e2a8a1/9/debian-10/rootfs/opt/bitnami/scripts/libdrupal.sh#L124-L151
> 
> You can see in your logs appear that the application can connect to the database, and something fails when the process runs the command `drush`.
> 
> I think that the application directory wasn't persisted, because of this:
> https://github.com/bitnami/bitnami-docker-drupal/blob/46db88088158c6a3aa361acfc6992ff0f8928b8c/9/debian-10/prebuildfs/opt/bitnami/scripts/libpersistence.sh#L105-L122
> 
> Could you try with `DRUPAL_SKIP_BOOTSTRAP` set to `no`?

If set this environment "DRUPAL_SKIP_BOOTSTRAP" to "no", database content will be deleted the tables will be dropped. How to avoid this?

**Comment by Mauraza** [comment]
Hi @nzlatev,

That way exists "DRUPAL_SKIP_BOOTSTRAP" to no initialize the database, but you get an error. Could you check if your database it's correct? For example, compare with a database just initialize. 
Always you can restore a backup after the drupal starts.

**Comment by nzlatev** [comment]
> Hi @nzlatev,
> 
> That way exists "DRUPAL_SKIP_BOOTSTRAP" to no initialize the database, but you get an error. Could you check if your database it's correct? For example, compare with a database just initialize.
> Always you can restore a backup after the drupal starts.


MySQL database is correct and accessible. Drupal site running when "DRUPAL_SKIP_BOOSTRAP" is set to "no" and new installation is ok. Drush updatedb checking failed due to missing settings.php file. Drush get the database credentials from this file, but for some reason mountPath "/bitnami/drupal" (azurefile-premium) overwrite "local" /bitnami/drupal directory and the drupal's bash scripts failed with validation and initialization. Did you test to deploy drupal site on AKS private cluster?

**Comment by Mauraza** [comment]
Hi @nzlatev,


> for some reason mountPath "/bitnami/drupal" (azurefile-premium) overwrite "local" /bitnami/drupal directory and the drupal's bash scripts failed with validation and initialization.

If you check these lines, you can see that this line appears in your logs:
https://github.com/bitnami/bitnami-docker-drupal/blob/79c95a60592f5ffceb252047f6ad547953e2a8a1/9/debian-10/rootfs/opt/bitnami/scripts/libdrupal.sh#L124-L125
It seems your mountPath is empty 
https://github.com/bitnami/bitnami-docker-drupal/blob/46db88088158c6a3aa361acfc6992ff0f8928b8c/9/debian-10/prebuildfs/opt/bitnami/scripts/libfs.sh#L69-L77
