### ISSUE TITLE
How to chanage DRUPAL_DATA_TO_PERSIST to the whole drupal root directory

### ISSUE THREAD

**Issue by ddfiberglass** [bitnami/bitnami-docker-drupal#124]
I used bitnami/drupal as my base image, and added some modules to my own image ddfiberglass/drupal. 

```
FROM bitnami/drupal:9

RUN cd /opt/bitnami/drupal && COMPOSER_MEMORY_LIMIT=-1 composer require drupal/smtp drupal/field_permissions drupal/search_api drupal/facets drupal/chosen drupal/profile drupal/metatag drupal/pathauto drupal/geofield drupal/field_group drupal/leaflet drupal/geocoder drupal/geolocation drupal/gin:^3.0@alpha --update-with-dependencies
```

Than I use helm install bitnami/drupal chart (with my own image, and  changed something in values.yaml) in a K3S cluster.

`helm install dd -f values.yaml bitnami/drupal
`

But some drupal modules require extra js files, and I need to download it to the /libraries directory. 

I want to change the DRUPAL_DATA_TO_PERSIST to the whole drupal root directory, so I can mkdir libraries, and download the js files directly, while not in the pod/container.

How to change: DRUPAL_DATA_TO_PERSIST:-sites/ themes/ modules/ profiles/ ? to the whole drupal root directory?

**Comment by rafariossaa** [comment]
Hi,
  Could you create your image with those files already downloaded ?.
  The `DRUPAL_DATA_TO_PERSIST` contains subdirectories from the drupal root directory and are used by this [function](https://github.com/bitnami/bitnami-docker-drupal/blob/55264d16670cde3b1d8f13c46c3ba890a19f67f2/9/debian-10/prebuildfs/opt/bitnami/scripts/libpersistence.sh#L27). It is not possible to change that value and make it work. Some more changes would be needed in the initialization logic.

**Comment by ddfiberglass** [comment]
@rafariossaa , OK, Thanks. I will try your way to fix it. Then I will close the issue.

**Comment by ddfiberglass** [comment]
I have fix it, check the files and Dockerfile for example: https://github.com/ddfiberglass/drupal_Dockerfile .
And the image is built in hub.docker.com/r/ddfiberglass/drupal .
If there is any better ways, please let me know.

**Comment by rafariossaa** [comment]
Hi,
  I am happy you were able to solve the issue, I think you approach is good.
  Thanks for sharing it.
