### ISSUE TITLE
Image does not work

### ISSUE THREAD

**Issue by ducarrozb** [bitnami/bitnami-docker-drupal#126]
Hi, I'm trying since days to make work your image, but unfortunately there is a problem. Your image does not come up. Yesterday morning the demo was at least working, but today, none of all of your solution works.
On my testserver is no firewall enabled.

`docker pull bitnami/drupal`
`docker run bitnami/drupal`
```
drupal 07:07:08.46 
drupal 07:07:08.47 Welcome to the Bitnami drupal container
drupal 07:07:08.47 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-drupal
drupal 07:07:08.47 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-drupal/issues
drupal 07:07:08.47 
drupal 07:07:08.47 INFO  ==> ** Starting Drupal setup **
drupal 07:07:08.50 INFO  ==> Configuring PHP options
drupal 07:07:08.51 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
drupal 07:07:08.55 WARN  ==> Hostname mariadb could not be resolved. This could lead to connection issues
drupal 07:07:08.55 ERROR ==> The DRUPAL_DATABASE_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow a blank password. This is only recommended for development environments.

```

**Comment by alvneiayu** [comment]
hi @ducarrozb 

To run our drupal image, you need to declare some environment variables to configure the container image (docker run using --env option). In your case, to set up a password using DRUPAL_DATABASE_PASSWORD or to ALLOW_EMPTY_PASSWORD=yes.

I suggest you to take a look the [bitnami docker drupal](https://github.com/bitnami/bitnami-docker-drupal) repository.

There you can find a Readme with some information that I think it will can help you.

Let me know If I can help you with something else.

Thanks a lot for your time

Álvaro

**Comment by ducarrozb** [comment]
Hi Álvaro,

Thank you for your response. The issue was the same as issue 125: https://github.com/bitnami/bitnami-docker-drupal/issues/125
and has been solved.
Regards,
bdu
