### ISSUE TITLE
Drupal 9.2.4 is already out for 4 days, Your bot is still not update

### ISSUE THREAD

**Issue by ddfiberglass** [bitnami/bitnami-docker-drupal#133]
Drupal 9.2.4 is out on August 13th, but it's not update yet. Please check, 
Also, the https://hub.docker.com/r/bitnami/drupal is not update, https://hub.kubeapps.com/charts/bitnami/drupal is not update.

**Comment by pablogalegoc** [comment]
Hi @ddfiberglass! Thank you for your interest, there are some instances where releases get delayed. In this case our pipeline is reporting test failures for Drupal, so once they are addressed you can expect to see the new version. Unfortunately I cannot give you an ETA on this.

**Comment by pablogalegoc** [comment]
@ddfiberglass released https://github.com/bitnami/bitnami-docker-drupal/releases/tag/9.2.4-debian-10-r0

**Comment by ddfiberglass** [comment]
Thanks.
