### ISSUE TITLE
Update base url for drupal 9

### ISSUE THREAD

**Issue by schroedt** [bitnami/bitnami-docker-drupal#137]
**Description**

I would like to update my side from `test.example.com` to `drupal.example.com`. How can this be done?
`settings.php` seems not using `$base_url` anymore.

**Steps to reproduce the issue:**

1-

**Describe the results you received:**

-
**Version**

drupal9

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by pablogalegoc** [comment]
Hi @schroedt,

According to [Removed base_url option from settings.php](https://www.drupal.org/node/2529168), _alternatives are to rewrite the request url with the help of `.htaccess` files_. You can find them in the container with
```
docker exec -it drupal_container find / -name .htaccess 2> /dev/null
```
AFAIK you'll have to [customize the image](https://github.com/bitnami/bitnami-docker-drupal#customize-this-image) if you want to modify these files

**Comment by schroedt** [comment]
Therefore, there is not other possibility for updating the base URL, than re-installing from scratch (and somehow importing a data backup)?

**Comment by pablogalegoc** [comment]
It is my understanding, yes. There's a section on [maintenance](https://github.com/bitnami/bitnami-docker-drupal#maintenance) in the README.
