### ISSUE TITLE
How to persist composer.json?

### ISSUE THREAD

**Issue by ximo1984** [bitnami/bitnami-docker-drupal#138]
**Description**

How can I install a composer library automatically when the site is created? I would like to do it automatically without having to enter the container. Could it be persisted compose.json?

**Comment by rafariossaa** [comment]
Hi, 
  Where does this file need to be ? Did you try to put it in the `drupal_data` volume ?

**Comment by ximo1984** [comment]
Hi,

I need to install more packages with composer to the drupal composer file, so I thought that one idea could be use a personal composer.json. Do you have any idea more?

Thank you.

**Comment by rafariossaa** [comment]
Hi, 
> Do you have any idea more?

  No, I am sorry.

**Comment by ximo1984** [comment]
Ok thank you.
