### ISSUE TITLE
Any plans to upgrade to PHP version 8.0 or higher for Drupal 9.3.0

### ISSUE THREAD

**Issue by ddfiberglass** [bitnami/bitnami-docker-drupal#142]
Dear Sir/Madam,

Drupal 9.3.0 is recommended to upgrade to PHP version 8.0 or higher for the best ongoing support. (Now the PHP Version is 7.4).

Any plans for the PHP Version upgrade?

Best regards,
David

**Comment by juan131** [comment]
Hi @ddfiberglass 

You're completely right! The recommended PHP version is 8.0 for Drupal 9, see https://www.drupal.org/docs/system-requirements/php-requirements

Let me check with the team if there's a special reason why we're using `7.4`. I'll keep you updated.

**Comment by juan131** [comment]
It seems that Drupal recommended `7.4` at the time we added support for the branch 9. However, they're recommending `8.0` now so I'll file a task to use `8.0`.

Thanks for reporting it.

**Comment by ddfiberglass** [comment]
> It seems that Drupal recommended `7.4` at the time we added support for the branch 9. However, they're recommending `8.0` now so I'll file a task to use `8.0`.
> 
> Thanks for reporting it.

Thanks @juan131 . I  have seen the new docker images upgraded to PHP 8.1.

**Comment by carrodher** [comment]
Yes, @ddfiberglass from `9.3.0-debian-10-r15` PHP 8.1 is being used, see https://github.com/bitnami/bitnami-docker-drupal/commit/97730d0afc1a4f8a7ba80ec3434ba84d2394468f

Thanks again for letting us know!
