### ISSUE TITLE
Process of running upgraded container stuck at 'drush updb'

### ISSUE THREAD

**Issue by derrekc** [bitnami/bitnami-docker-drupal#143]
### Name and Version

bitnami/drupal:9.3.5

### What steps will reproduce the bug?

In Debian VM environment, running Docker:
Updated Dockerfile to reference `FROM bitnami/drupal:9.3.5`, commit to group GitLab repository,
Await successful CI pipeline run on VM with existing persistent volume for Drupal

Check status of logs for container via `docker logs -f <container_name>`

```
drupal 18:00:05.47 DEBUG ==> Upgrading Drupal database with drush...
 -------- ------------------ ------------- ------------------------------------ 
  Module   Update ID          Type          Description                         
 -------- ------------------ ------------- ------------------------------------ 
  media    modify_base_fiel   post-update   Updates stale references to         
           d_author_overrid                 Drupal\media\Entity\Media::getCurr  
           e                                entUserId.                          
  node     modify_base_fiel   post-update   Updates stale references to         
           d_author_overrid                 Drupal\node\Entity\Node::getCurren  
           e                                tUserId.                            
 -------- ------------------ ------------- ------------------------------------ 


 Do you wish to run the specified pending updates? (yes/no) [yes]:
```

### What is the expected behavior?

Expected to see `drush updb` run successfully without human interaction when container is re-deployed.

### What do you see instead?

The process of starting the container is interrupted because the `drush updb` command is awaiting user feedback.
(However, the container itself is active.)

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-drupal#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
