### ISSUE TITLE
drupal image not customizable?

### ISSUE THREAD

**Issue by dirkpauli** [bitnami/bitnami-docker-drupal#147]
### Name and Version

 bitnami/bitnami-docker-drupal:9.4.1

### What steps will reproduce the bug?

- using the plain image, evrything is fine.
- building an own image with the following docker file,  also results in an working container:
FROM docker.io/bitnami/drupal:9
USER 1001
WORKDIR /opt/bitnami/drupal
RUN echo "ok" >./dptest

- but using this, the container stops after line "INFO  ==> Trying to connect to the database server":
# syntax=docker/dockerfile:1
FROM docker.io/bitnami/drupal:9
USER 1001
WORKDIR /opt/bitnami/drupal
RUN composer require google/recaptcha "^1.2"

The composer line is exchangable, everything "meaningful" that is done there leads to a stopped container. 

### What is the expected behavior?

the above example should work out in a running drupal container with integrated google recaptcha

### What do you see instead?

 drupal 20:34:27.59 INFO  ==> Configuring Apache ServerTokens directive
 drupal 20:34:27.62 INFO  ==> Configuring PHP options
 drupal 20:34:27.62 INFO  ==> Setting PHP opcache.enable option
 drupal 20:34:27.63 INFO  ==> Setting PHP expose_php option
 drupal 20:34:27.65 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
 drupal 20:34:27.75 INFO  ==> Restoring persisted Drupal installation
 drupal 20:34:27.79 INFO  ==> Trying to connect to the database server
--> then the container stops

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.

**Comment by ddfiberglass** [comment]
> ### Name and Version
> bitnami/bitnami-docker-drupal:9.4.1
> 
> ### What steps will reproduce the bug?
> * using the plain image, evrything is fine.
> * building an own image with the following docker file,  also results in an working container:
>   FROM docker.io/bitnami/drupal:9
>   USER 1001
>   WORKDIR /opt/bitnami/drupal
>   RUN echo "ok" >./dptest
> * but using this, the container stops after line "INFO  ==> Trying to connect to the database server":
> 
> # syntax=docker/dockerfile:1
> FROM docker.io/bitnami/drupal:9 USER 1001 WORKDIR /opt/bitnami/drupal RUN composer require google/recaptcha "^1.2"
> 
> The composer line is exchangable, everything "meaningful" that is done there leads to a stopped container.
> 
> ### What is the expected behavior?
> the above example should work out in a running drupal container with integrated google recaptcha
> 
> ### What do you see instead?
> drupal 20:34:27.59 INFO ==> Configuring Apache ServerTokens directive drupal 20:34:27.62 INFO ==> Configuring PHP options drupal 20:34:27.62 INFO ==> Setting PHP opcache.enable option drupal 20:34:27.63 INFO ==> Setting PHP expose_php option drupal 20:34:27.65 INFO ==> Validating settings in MYSQL_CLIENT_* env vars drupal 20:34:27.75 INFO ==> Restoring persisted Drupal installation drupal 20:34:27.79 INFO ==> Trying to connect to the database server --> then the container stops
> 
> ### Additional information
> _No response_

This **google/recaptcha "^1.2"** is not right, you should use: google/recaptcha:^1.2 .
I build a docker image also based on bitnami/drupal. check:
