### ISSUE TITLE
Error executing 'postInstallation': mysqlCore.checkConnection is not a function

### ISSUE THREAD

**Issue by ababushkin** [bitnami/bitnami-docker-drupal#15]
I followed the instructions found in README and keep receiving the following error when the drupal container is starting up:

Error executing 'postInstallation': mysqlCore.checkConnection is not a function

Any ideas on how to get around it?

I'm running Docker 1.11.0, build 4dc5990 with docker-compose 1.7.0, build 0d7bf73 on OSX

Thanks in advance.

**Comment by sameersbn** [comment]
Thanks for reporting the issue @ababushkin. We're working on the fix. Please use the `bitnami/drupal:8.1.7-r0` release until we release the fix. Thanks for understanding.

**Comment by chipironcin** [comment]
Hi @ababushkin 
It should be fixed now. Sorry for the inconvenience, we didn't update the dependencies accordingly when bumped the new version.

Dont hesitate in opening this thread again if you still find issues with the image.

Regards

**Comment by ababushkin** [comment]
You guys are quick! I'll check it out tonight and let you know if I have any troubles

👍
