### ISSUE TITLE
PHP 7 option?

### ISSUE THREAD

**Issue by scottrigby** [bitnami/bitnami-docker-drupal#53]
When using k8s (for example [Helm/Charts/Drupal](https://github.com/kubernetes/charts/tree/master/stable/drupal)), what is the best way to include PHP 7? Or… would this be a new feature we could work on?

**Comment by prydonius** [comment]
Hey @scottrigby, for a quick try, I was able to get Drupal running on PHP 7 by modifying the Dockerfile in this repo:
```
diff --git a/Dockerfile b/Dockerfile
index 15c8e0d..8a4a971 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -11,8 +11,8 @@ RUN install_packages libssl1.0.0 libaprutil1 libapr1 libc6 libuuid1 libexpat1 li
 
 # Additional modules required
 RUN bitnami-pkg unpack apache-2.4.23-11 --checksum e4876fc1514082af221105319ddc8f069e7e2305dded70633bbf9a5973f2d9be
-RUN bitnami-pkg install php-5.6.28-1 --checksum e6a6a80ccd36d3e6c4edd4c6dd97d6247534584f023bf89dda6d13728138ca37
-RUN bitnami-pkg install libphp-5.6.28-1 --checksum c7a1df270fad99fbcff23506574ec1467bac4e0f0f6d0bd34bf310446ec5d7f5
+RUN bitnami-pkg install php-7.1.0-1 --checksum 069f80b98b29998601f10685462b2f499cd95c5c56d036b4a3d2b5f64d310028
+RUN bitnami-pkg install libphp-7.1.0-0 --checksum 7ecdcdcfcedf67d67e46260f3669bb61c18a6e062c5576ce438270a39540c98a
 RUN bitnami-pkg install mysql-client-10.1.19-1 --checksum 2d946c8ee3e2e845f68a5cf3751d6477d88af194d263842797fe50a44414a173
 RUN bitnami-pkg install drush-8.0.5-1 --checksum cdea2d5067ef67bcda7e5cfe96798c2d6e0167578395fac2d7a5f92a814ecc69
```

We're going to look into the level of support for Drupal on PHP 7 and will likely update this image, and any other PHP-based apps, in the coming weeks. We'll keep this issue updated on what we find.

Thanks for the suggestion :)

**Comment by scottrigby** [comment]
Since the parameterization proposal in #69 was not accepted, and the Drupal version directory structure has now been started (/8)  I'll keep this issue open so we can discuss how/if PHP 7 will be supported in this repo.

**Comment by juan131** [comment]
I agree with you @scottrigby ! We should keep it open until Drupal is released with php 7. 
We plan to move some applications such as Drupal to php 7 soon. Let's let it open until then.

**Comment by scottrigby** [comment]
@juan131 Here is a matrix of the supported Drupal core versions, and PHP versions https://www.drupal.org/docs/7/system-requirements/php#php_required

As you can see, both Drupal 7 and Drupal 8 (supported Drupal core versions) support PHP 7 now.

**Comment by juan131** [comment]
@scottrigby thanks for sharing the info. As I mentioned we are planning some application to php 7 such as Drupal, Joomla! or WordPress. Hopefully, they will be published with php 7 very soon.

**Comment by sameersbn** [comment]
@scottrigby the PHP version has been update to `7.0` since release `8.2.6-r2`.
Thanks for using this image.
