### ISSUE TITLE
Parameterize Drupal version

### ISSUE THREAD

**Issue by scottrigby** [bitnami/bitnami-docker-drupal#68]
@prydonius per our chat, I was thinking we could pass the Drupal version with a Docker [--build-arg](https://docs.docker.com/engine/reference/builder/#arg) (pinned 7.x, 8.1.x, 8.2.x, 8.3.x or full tags).

I would guess for backwards compatibility you'd want to default `${app_version:-8.2.6-r0}` (whatever your most recent built image is).

It makes me wonder if we could possibly use this strategy for #53 too?

**Comment by juan131** [comment]
The discussion about this issue has been moved to  https://github.com/bitnami/bitnami-docker-drupal/pull/69
