### ISSUE TITLE
Mount drupal/core just like modules and themes

### ISSUE THREAD

**Issue by scottrigby** [bitnami/bitnami-docker-drupal#83]
**Description**

Currently, `/bitnamidrupal` is mounted, and that allows modification (`if hostPath` is specified) for development. However, this does not allow development of Drupal core, which is a shame.

**Proposal**

- Copy Drupal core initially into `/bitnami/drupal/core`
- Create a symlink from `/opt/bitnami/drupal/core -> /bitnami/drupal/core` (to match `/opt/bitnami/drupal/modules` and `/opt/bitnami/drupal/themes`)

**Question**

I would open a PR to do this, but it's unclear to me if this part of the bitnami build chain is in a public repo, or currently hidden.

**Comment by scottrigby** [comment]
CC @prydonius

**Comment by javsalgar** [comment]
Thanks for the suggestion. We have some concerns regarding how this would affect the upgrade process. We are looking into it to see if we can make it an optional mount.

**Comment by scottrigby** [comment]
@javsalgar OK great 👍 Here is a helm charts PR that adds the ability to already develop the stable/drupal chart: https://github.com/kubernetes/charts/pull/1084. But without mounting core as well, only contrib development is possible there. However, if we can mount Drupal core too, core development (even testing patches etc) will also be possible.

**Comment by scottrigby** [comment]
@javsalgar In fact, why not mount the entire `/opt/bitnami/drupal` to `/bitnami/drupal`? For Drupal development (even for advanced site builders) everything in the Drupal ROOT should be mounted. See http://cgit.drupalcode.org/drupal/tree/?h=8.3.x. 

I'm curious how this would affect the upgrade process at all? It seems someone made an arbitrary decision in the past to mount modules and themes, perhaps thinking this is all developers should need to touch? If so, this is definitely not the case.

**Comment by scottrigby** [comment]
@javsalgar @prydonius  If someone can point me to where the modules/themes symlinking happens (it seems [not to happen in this repo](https://github.com/bitnami/bitnami-docker-drupal/search?utf8=%E2%9C%93&q=modules&type=)) I would be happy to make a PR in the correct location, and then we can test the upgrade process through that PR, and see?

**Comment by prydonius** [comment]
Hey @scottrigby, I took another look at this. The issue is that if you persist everything in `/opt/bitnami/drupal` then you can't upgrade between Drupal versions. There's an interesting explanation about this in https://github.com/docker-library/docs/tree/master/drupal#volumes too.

Following the workaround from that example, you can do something similar with the Bitnami container by:

```
docker-compose up -d
# wait for drupal to be ready
docker cp `docker-compose ps -q drupal`:/opt/bitnami/drupal ./drupal
```

This copies the initialised `/opt/bitnami/drupal` folder from the container to your host. Now you can mount this back in the container from the host by adding a mount in docker-compose.yaml:

```
diff --git a/docker-compose.yml b/docker-compose.yml
index 7174095..edd289f 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -13,6 +13,7 @@ services:
       - '80:80'
       - '443:443'
     volumes:
+      - './drupal:/opt/bitnami/drupal'
       - 'drupal_data:/bitnami/drupal'
       - 'apache_data:/bitnami/apache'
       - 'php_data:/bitnami/php'
```

and finally recreate the container to get your mounted `/opt/bitnami/drupal`:

```
docker-compose up -d drupal
```
