### ISSUE TITLE
Add environment variable to specify database name

### ISSUE THREAD

**Issue by bptarpley** [bitnami/bitnami-docker-drupal#85]
There's currently no way to set the database name (defaults to bitnami_drupal).  Please add env variable to be able to specify db name so multiple instances can use same database server :)

**Comment by jotadrilo** [comment]
Hi @bptarpley,

As you mentioned, I'm afraid that this is not currently supported for this container.

However, as it seems a beneficial feature, we will investigate the possibility to implement it in the future.

Thanks for your feedback!

**Comment by juan131** [comment]
Hi everybody

A new revision of the Docker Image (8.4.2-r1) hast just been released and now the Bitnami Docker Drupal Image supports using an existing database.

More info at: https://github.com/bitnami/bitnami-docker-drupal#use-an-existing-database

Please feel free to use this new image and give us any feedback about this new feature.

**Comment by bptarpley** [comment]
Thank you for implementing this!  Y'all are the best.
