### ISSUE TITLE
Directory "profiles" can persist too

### ISSUE THREAD

**Issue by jose-carmona** [bitnami/bitnami-docker-drupal#86]
**Description**

Drupal nami  installer create symlinks for `sites`, `themes` and `modules` directories to permit persist data. Installer can create symlink for `profiles` directory too.
 
**Steps to reproduce the issue:**

1. Run drupal
2. Wait to installer ends

**Describe the results you received:**

Diretory `/opt/bitnami/drupal`:
```
lrwxrwxrwx  1 root root     21 Sep 19 10:59 sites -> /bitnami/drupal/sites
lrwxrwxrwx  1 root root     22 Sep 19 10:59 themes -> /bitnami/drupal/themes
lrwxrwxrwx  1 root root     23 Sep 19 10:59 modules -> /bitnami/drupal/modules
drwxr-xr-x  1 root root   4096 Sep 19 10:59 profiles
```

**Describe the results you expected:**

Diretory `/opt/bitnami/drupal`:
```
lrwxrwxrwx  1 root root     21 Sep 19 10:59 sites -> /bitnami/drupal/sites
lrwxrwxrwx  1 root root     22 Sep 19 10:59 themes -> /bitnami/drupal/themes
lrwxrwxrwx  1 root root     23 Sep 19 10:59 modules -> /bitnami/drupal/modules
lrwxrwxrwx  1 root root     23 Sep 19 10:59 profiles -> /bitnami/drupal/profiles

```

**Comment by silviofdez** [comment]
Thanks for the feedback. I think you are right. We will gonna fix that.

**Comment by scottrigby** [comment]
Can we close this issue?

**Comment by jose-carmona** [comment]
It works for me!

Thank you very much!
