### ISSUE TITLE
Install issue on Kubernetes

### ISSUE THREAD

**Issue by skorski** [bitnami/bitnami-docker-drupal#89]
**Description**

I'm trying to install this container on kubernetes.  I've tried the install with the default kubernetes chart as well as with a MySQL db provided by azure.  In both cases, the container fails to start.

**Steps to reproduce the issue:**

```
helm install stable/drupal
```
https://github.com/kubernetes/charts/tree/master/stable/drupal

**Describe the results you received:**

**Describe the results you expected:**
I expected the container to come up in the same way as it does with a docker compose up.

**Additional information you deem important (e.g. issue happens only occasionally):**

```
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing drupal
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at drupalsql-1680-mysql.mysql.database.azure.com:3306
mysql-c INFO  MySQL server listening and working at drupalsql-1680-mysql.mysql.database.azure.com:3306
drupal  INFO  Passing wizard, please be patient
Error executing 'postInstallation': Timeout: did not get to load all resources on this page
nami    TRACE Error: Error executing 'postInstallation': Timeout: did not get to load all resources on this page
    at Browser.exec (/opt/bitnami/nami/node_modules/nami-core/lib/browser/index.js:447:15)
    at Object.$app.helpers.passWizard (/root/.nami/components/com.bitnami.drupal/helpers.js:37:6)
    at Component.$app.postInstallation (/root/.nami/components/com.bitnami.drupal/main.js:33:18)
    at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
    at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)
    at Component.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
    at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
    at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:518:30)
    at NamiParser.parse (/opt/bitnami/nami/node_modules/cmd-parser/index.js:742:14)
    at NamiCliApp.parse (/opt/bitnami/nami/cli/nami-app.js:592:17)
    at NamiCliApp.exec (/opt/bitnami/nami/cli/nami-app.js:599:12)
    at Object.<anonymous> (/opt/bitnami/nami/index.js:10:19)
    at Module._compile (module.js:541:32)
```

The container fails to completely come up but it does appear to make the necessary tables in MySQL.

When the container is respawned it gives a different error:
```
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing drupal
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at drupalsql-1680-mysql.mysql.database.azure.com:3306
mysql-c INFO  MySQL server listening and working at drupalsql-1680-mysql.mysql.database.azure.com:3306
drupal  INFO  Passing wizard, please be patient
Error executing 'postInstallation': No INPUT matching 'site_name'
```

**Version**

- Output of `docker version`:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T16:55:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

This issue is also open with the helm charts (https://github.com/Azure/helm-charts/issues/76) but it would be great to get some pointer on what this error actually means.  I can also see the bitnami loading page as the `passing wizard` command is running.

**Comment by skorski** [comment]
As I investigate more, I'm not sure this is strictly a kubernetes issue.  I tried the docker container alone on a VM in azure while pointed towards the azure mysqldb and I got the 
```
Error executing 'postInstallation': No INPUT matching 'site_name'
```
error.  Is there any reason this container shouldn't work with the azure hosted mysql?

**Comment by tompizmor** [comment]
Hello @skorski,

I don't think the issue is Kubernetes specific. The error means that there was not enough time to pass the Drupal installation wizard. 

It seems that populating the database takes much more time when using an Azure Database for MySQL. When the initialization reaches the timeout, only 38/68 tables have been created in the Azure database. 
I am not sure if there are some parameters that could be tweaked in the default configuration or maybe using a bigger instance will help.

**Comment by skorski** [comment]
at @tompizmor Thank you for the direction!  I now agree this is not kubernetes specific.  When I up the initial health check to 900 seconds and use maria in kubernetes, it stands up as expected.  I would assume if the azure mysql db is that slow for creation it won't be very quick for drupal at all.  Would you think that's reasonable?

I'm really surprised the azure mysql instance is that much slower than the mariadb instance in kubernetes.  I really appreciate your help.
