### ISSUE TITLE
Install profile support

### ISSUE THREAD

**Issue by scottrigby** [bitnami/bitnami-docker-drupal#91]
I'm making an issue rather than a PR right now because some of the required changes are in files that aren't in this repo, and I'm not sure where they live: specifically the bitnami drupal `main.js` installer file. Adding diffs for files including that one.

This one is for this repo, the `docker-compose.yml` file:
```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 64687f9..d7f3766 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -19,6 +19,8 @@ services:
       - DRUPAL_DATABASE_USER=bn_drupal
       - DRUPAL_DATABASE_NAME=bitnami_drupal
       - ALLOW_EMPTY_PASSWORD=yes
+      ## Optionally specify a Drupal install profile.
+      # - DRUPAL_PROFILE=demo_umami
     ports:
       - '80:80'
       - '443:443'
```

Simple (working) change to `main.js`:
```diff
--- main.js	2018-07-16 16:19:04.000000000 -0400
+++ main-override.js	2018-07-16 16:19:15.000000000 -0400
@@ -3,6 +3,7 @@
 const handlerSelector = require('./lib/handlers/selector');
 const volumeFunctions = require('./lib/volume')($app);
 const componentFunctions = require('./lib/component')($app);
+const DRUPAL_PROFILE = process.env.DRUPAL_PROFILE || 'standard';
 
 $app.postUnpackFiles = function() {
   // Needed so we can call to $app.start and similar while initiasing as non-root
@@ -49,6 +50,7 @@
     $app.info('Installing Drupal with drush...');
     $os.runProgram('drush', [
       'site:install',
+      `${DRUPAL_PROFILE}`,
       `--db-url=mysql://${databaseHandler.connection.user}:${databaseHandler.connection.password}`
         + `@${databaseHandler.connection.host}:${databaseHandler.connection.port}/${databaseHandler.connection.name}`,
       `--account-name=${$app.username}`,
```

Also I thought it may be worth adding the install profile to `inputs.json` (the default is “standard”), but when I did there was an error that those keys are somewhere validated along the way… as in, they don’t just pass directly from there to the `$app` object in `main.js`, otherwise I would have gone that route 🤷‍♂️  But maybe if someone can help me see where that happens, I can propose a change in the appropriate place that would allow that, so it would be more in line with existing ENV vars to variables like username, password, etc.

**Comment by juan131** [comment]
At this moment, the repository where the Nami modules code resides is not public. However, we really appreciate this kind of suggestions like yours!! Thanks so much for it!

I'll create a task to include the logic so you can use that env. variable (such as **DRUPAL_PROFILE**) to configure the Drupal installation profile. We'll keep you updated

**Comment by scottrigby** [comment]
@juan131 I added a few comments in https://github.com/kubernetes/charts/pull/6681, but I think we can follow up here. I see the debian 8 jessie tag is built with this change (which was very fast BTW!), but can you check on the debian 9 stretch tag? I'm wondering if the CI is just taking a long time, or if it may be stuck? (I ask because - I assume - the underlying build process is also not public?). Once that's built, and we can verify it works, I think we can close this issue. Thanks!

**Comment by juan131** [comment]
Hi @scottrigby 

I juste released a new version of this Docker Image including the changes you suggested. Now you can use the env. variable **DRUPAL_PROFILE** to configure the Drupal Installation Profile.

Images including this new feature:
 - Debian 9:  **8.5.5-debian-9-r9**
 - Debian 8:  **8.5.5-debian-8-r10**
 - Oracle Linux:  **8.5.5-ol-7-r12**

We also update the Drupal Official Helm Chart so you can use this on K8s too. See https://github.com/kubernetes/charts/pull/6681

Please feel free to use and provide us feedback! Thanks so much for reporting it.

PD: regarding Debian Stretch. I was working on other stuff and I did not have time on others OS yesterday. Please note we do a huge battery of tests internally before releasing on every distro.

**Comment by scottrigby** [comment]
@juan131 tested and works 👍 💯
