### ISSUE TITLE
xdebug

### ISSUE THREAD

**Issue by scottrigby** [bitnami/bitnami-docker-drupal#92]
How would one go about installing xdebug with (or extending) this image?

**Comment by carrodher** [comment]
You can install packages using the `install_packages` command. You can do it in the Dockerfile or inside the container by running
```
install_packages YOUR_PACKAGE
```

Below you can find an example:
https://github.com/bitnami/bitnami-docker-drupal/blob/f9a8078595cf7da163c991c134ec8a4071b0c9b9/8/debian-9/Dockerfile#L5

Is this solution valid for you?

**Comment by scottrigby** [comment]
`install_packages` seems handy, so I used it (otherwise I did `apt-get update && apt-get install -y` and it also worked fine). More is needed though to install xdebug for local development.

However, I was able to get it to work. Posting below in case it helps someone else.

PS, I'm curious why `docker-php-ext-enable` isn't included in the image. In any case, this works 👍 

```dockerfile
FROM bitnami/drupal:8

# Requires autoconf for phpize, and build-essential for C compiler.
RUN install_packages autoconf build-essential
# Bitnami image does not include `docker-php-ext-enable`, so we need to add the
# zend_extension information ourselves.
COPY xdebug.ini /opt/bitnami/php/etc/conf.d/
RUN pecl install xdebug \
    && echo "zend_extension=/opt/bitnami/php/lib/php/extensions/xdebug.so" >> /opt/bitnami/php/etc/conf.d/xdebug.ini
```

Here's my `xdebug.ini` file:
```ini
xdebug.remote_enable = On
xdebug.max_nesting_level = 256
xdebug.remote_host = docker.for.mac.host.internal
xdebug.remote_connect_back = 0
xdebug.remote_autostart = 0
; See https://www.drupal.org/docs/8/system-requirements/drupal-8-php-requirements#xdebug
xdebug.show_exception_trace = 0
xdebug.remote_port = 9001
```

**Comment by carrodher** [comment]
We are glad that you were able to fix the issue. Also, thank you for the additional information. We are using `minideb` as the base image, an image designed to be light while including basic packages, of course adding versatility so that the user can customize it and install everything necessary.

If you have any other questions, please do not hesitate to let us know.
