### ISSUE TITLE
Allow changing WORKDIR in Dockerfile

### ISSUE THREAD

**Issue by scottrigby** [bitnami/bitnami-docker-drupal#94]
**Description**

I'd like to change `WORKDIR` in an extended image, so that when you exec into the container, it will be into the `bitnami/drupal` directory, as a convenience step for developers who want to run `drush` commands (as they'll only work within the Drupal root).

The problem is if I add this to a Dockerfile, some init functions don't work (I get the "it works!" Apache screen at localhost). This may be because they assume to be running at `/`:

```docker
FROM bitnami/drupal
WORKDIR /bitnami/drupal
ENTRYPOINT ["/app-entrypoint.sh"]
CMD ["/run.sh"]
```

If it seems like too large a thing to abstract, let me know and I'll close this issue. It would be a nice improvement though. Note, I would just open a PR to fix this, but some of these scripts are not in public repos.

**Comment by tompizmor** [comment]
Hi @scottrigby,

I think it should be possible to define a custom WORKDIR in an extended image and Drupal should still initialize properly. If that is not the case, it looks like something that it should be fixed. 
I am going to create a task to review this issue and try to fix it for future releases. 
We will update this issue as soon as we have more information.

**Comment by tompizmor** [comment]
Hi @scottrigby!!

This issue is already fixed with the new release of the Drupal images. 
Run `docker pull bitnami/drupal` to get the latest bitnami image and then you will be able to build your image with your custom Dockerfile.
