### ISSUE TITLE
v8.6.1: WORDPRESS_DATABASE_PASSWORD is empty or not set

### ISSUE THREAD

**Issue by emepetres** [bitnami/bitnami-docker-drupal#96]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

Drupal container is looking for "WORDPRESS_DATABASE_PASSWORD" at start up. As a workaround, defining the variable resolves the problem.

**Steps to reproduce the issue:**

1. In Kubernetes, deploy a MariaDB and its service, defining a database.
2. In Kubernetes, create a drupal deployment, defining the same database as before:
image: bitnami/drupal:8.6.1
MARIADB_HOST
DRUPAL_DATABASE_NAME
DRUPAL_DATABASE_USER
DRUPAL_DATABASE_PASSWORD
DRUPAL_USERNAME
DRUPAL_PASSWORD

**Describe the results you received:**
```
Welcome to the Bitnami drupal container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-drupal
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-drupal/issues

ERROR ==> The WORDPRESS_DATABASE_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
```

**Describe the results you expected:**

Normal start up of drupal:

```
Welcome to the Bitnami drupal container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-drupal
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-drupal/issues

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mysql:3306
mysql-c INFO  MySQL server listening and working at mysql:3306
mysql-c INFO  ==> Creating database drupal...
mysql-c INFO  ==> Granting access to drupal to the database drupal...
mysql-c INFO
mysql-c INFO  ########################################################################
mysql-c INFO   Installation parameters for mysql-client:
mysql-c INFO     Database User created: drupal
mysql-c INFO     Database Name created: drupal
mysql-c INFO     Database Password created: **********
mysql-c INFO     Database Host: mysql
mysql-c INFO     Database Port: 3306
mysql-c INFO     Database Root User: root
mysql-c INFO     Database Root Password: **********
mysql-c INFO   (Passwords are not shown for security reasons)
mysql-c INFO  ########################################################################
mysql-c INFO
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing drupal
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mysql:3306
mysql-c INFO  MySQL server listening and working at mysql:3306
drupal  INFO  Installing Drupal with drush...
drupal  INFO  Cleaning the cache..
drupal  INFO
drupal  INFO  ########################################################################
drupal  INFO   Installation parameters for drupal:
drupal  INFO     Username: drupal
drupal  INFO     Password: **********
drupal  INFO     Email: user@example.com
drupal  INFO     Blog Name: My blog
drupal  INFO   (Passwords are not shown for security reasons)
drupal  INFO  ########################################################################
drupal  INFO
nami    INFO  drupal successfully initialized
INFO  ==> Starting drupal...
INFO  ==> Starting httpd...
[Sun Oct 07 20:16:51.046847 2018] [ssl:warn] [pid 144] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Oct 07 20:16:51.141079 2018] [ssl:warn] [pid 144] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Oct 07 20:16:51.541739 2018] [ssl:warn] [pid 144] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Oct 07 20:16:51.542704 2018] [ssl:warn] [pid 144] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Oct 07 20:16:51.843603 2018] [mpm_prefork:notice] [pid 144] AH00163: Apache/2.4.35 (Unix) OpenSSL/1.1.0f PHP/7.1.22 configured -- resuming normal operations
[Sun Oct 07 20:16:51.843657 2018] [core:notice] [pid 144] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The error can probably be reproduce as well in a docker machine (don't have one at hand right now)

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Kubernetes on AWS.

**Comment by juan131** [comment]
Hi @emepetres 

As you can check, indeed the Nami logic is using **DRUPAL_DATABASE_PASSWORD**: https://github.com/bitnami/bitnami-docker-drupal/blob/master/8/debian-9/rootfs/drupal-inputs.json#L3

However, the **init.sh** file that checks **ALLOW_EMPTY_PASSWORD** is wrong:

https://github.com/bitnami/bitnami-docker-drupal/blob/master/8/debian-9/rootfs/init.sh

I just created a PR to fix it

**Comment by ricardocedex** [comment]
I´m trying to use tag 8.5.5 and the issue still remains, has anyone added this to this commit? In case not, how can i change init.sh from docker image init.sh?? thanks!

**Comment by juan131** [comment]
Hi @ricardocedex 

The tag **8.5.5** is a pretty old version of the Bitnami Drupal image (please note current one is **8.6.13**) so it's very likely to be affected by this issue (the patch was added on October 2018)

Is there any reason why you're still using an outdated version of Drupal? Couldn't you move the recent version of the container?

**Comment by ricardocedex** [comment]
Thanks for your quick response. I have a 8.5.5 drupal and I wanted to dockerize it. So I thought to use a bitnami/drupal to do it. That´s why i tried with these tag. I have changed the file with 'docker cp' and everything runs. However I don´t know how to get to drupal. I just can see apache working. In newer versions bitnami drupal the web was automatically available in port 80 of the container. ¿Where is it in this old version? Thanks for the feedback in any case!

**Comment by juan131** [comment]
Could you please detail (step by step) how you used `docker cp` to patch the file and how you start the Drupal container? 

> However I don´t know how to get to drupal. I just can see apache working. In newer versions bitnami drupal the web was automatically available in port 80 of the container

It seems that Drupal initialization was skipped for some reason and you just can see Apache. Could you share the container logs?

**Comment by ricardocedex** [comment]
I just used _**docker cp init.sh my_container:/init.sh**_ but when I tried to edit/recreate through portainer the image started as original. Finally I use the command with the machine stopped and then I started it and it worked. I have started to understand about persistence of containers.  With Drupal I have found that if I start http://host:port/drupal then it works. I was trying http://host:port because in latest tag it worked but I have realized that it doesn´t for old ones. However I doesn´t not worked for my machine, This image does not have ldap extension and when I tried to execute my drupal plugins seems to fail...I have tried with php-apache and it seems to have worked. When I update drupal I will try again with a latest tag. Thanks for the feedback!

**Comment by ricardocedex** [comment]
Thanks I will try that, i want to ask you another question. If I create a Volume, when you build an image, does the volume go inside the new image?

**Comment by carrodher** [comment]
You can’t mount volumes, as you can when working with containers. There is no `-v` option when running the `docker build` command. [Here](https://stackoverflow.com/questions/26050899/how-to-mount-host-volumes-into-docker-containers-in-dockerfile-during-build) you can find an extended discussion about this topic and the reasons why it is not supported.

**Comment by ricardoh34** [comment]
What I was really wondering was if in the new image I could bind the content of the volume, so when I deploy a container from the new image the data of the volume will stay the same and part of the new image. I ask this because I don´t still understand layers and how to build a new container properly. Thanks again

**Comment by juan131** [comment]
> if in the new image I could bind the content of the volume, so when I deploy a container from the new image the data of the volume will stay the same and part of the new image.

Do you mean to include the data in the image by default? That won't be using an "external" volume but including the content in the image instead.

If you want to know more about docker layers and how to create Dockerfiles, I recommend you the tutorial below:

https://engineering.bitnami.com/articles/best-practices-writing-a-dockerfile.html
https://github.com/juan131/dockerfile-best-practices
